name: niam
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Qo‘shimcha package’lar
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatar.png
    - assets/icons/notification.png
    - assets/icons/frame.png
    - assets/icons/fuelUp.png
    - assets/icons/hend.png
    - assets/icons/Chart2.png
    - assets/images/coin.png
    - assets/images/gift.png
    - assets/images/recommended1.png
    - assets/icons/
    - assets/images/
